### ISSUE TITLE
how to run it 

### ISSUE THREAD

**Issue by quickstreamingmedia** [owaiswiz/Freet#1]
how to run it ???

**Comment by quickstreamingmedia** [comment]
I did run ut its not playing even suing vpn where jjjio tav work well

**Comment by quickstreamingmedia** [comment]
when click on channel its not going to player
whats the issue

**Comment by quickstreamingmedia** [comment]
I have some work for you please contact me : quickstreamingmedia we can do some projects I will pay you

**Comment by quickstreamingmedia** [comment]
am waiting for you please respond

**Comment by owaiswiz** [comment]
Hello,
as you can see this is a personal project and as such tailored to my specific needs.

Anyways the idea of this project is that you run the player on a computer, and then you use freet app to control that player. For example, I have configured my tv with a raspberry pi that always runs the player.
So whenever I have to watch something, I use the app to control the player.

You can contact me at owaiswiz@gmail.com if you want to discuss any work.
